### ISSUE TITLE
Article “Model-driven Consistency Verification for Service-Oriented Applications” reading

### ISSUE THREAD

**Issue by pedroeml** [ESOM-2017-1/frost-lotus#5]
This is a general task, must be performed by each group member.

**Comment by vssesti** [comment]
I'm pretty sure everyone has read it by now and we can close this issue. I'll be waiting for confirmation.

**Comment by AnnyFigueira** [comment]
I've finished reading.

**Comment by masmangan** [comment]
Please, report status.

**Comment by ggsantos** [comment]
I've finished reading the article.

**Comment by vssesti** [comment]
It seems everyone is done.
