### ISSUE TITLE
Investigate the status of DIVERSITY

### ISSUE THREAD

**Issue by vssesti** [ESOM-2017-1/frost-lotus#7]
We *also* need to investigate how DIVERSITY currently stands and how well it works with the remainder of the Eclipse platform. Afterwards, some trivial examples should be executed on it.

**Comment by ggsantos** [comment]
The DIVERSITY platform is not currently available.

The platform known as Eclipse Formal Modeling Project will substitute DIVERSITY.

The Eclipse Modeling Project is currently being developed and there're no releases yet. It is possible to read about the project at https://projects.eclipse.org/proposals/eclipse-formal-modeling-project
